### ISSUE TITLE
provide new option gitr.echo_cmd defaulting to FALSE

### ISSUE THREAD

**Issue by malcook** [stufield/gitr#14]
The git function defaults its echo_cmd argument to FALSE:

https://github.com/stufield/gitr/blob/c5aebda2bf67827c6728f070d455ff6e4d3e33f1/R/git.R#L35 

Some gitr functions pass in FALSE for this, but most do not pass anything, e.g.

[git_recent_tag ](https://github.com/stufield/gitr/blob/c5aebda2bf67827c6728f070d455ff6e4d3e33f1/R/git-tag.R#L12)

It would be useful to be able to suppress all echoing of git commands through the use of an option, e.g.

```
options(gitr.echo_cmd=FALSE)
```

**Comment by stufield** [comment]
Hey, thanks for the issue!

I'll see what I can do ... generally I avoid forcing users to set global options (mostly because I hate having to do this myself as a user), but your issue highlights the need for some coding consistency.

I'll take a closer look and see how I can make things a bit smoother.

**Comment by stufield** [comment]
I assume in your post you meant
```
"The git function defaults its echo_cmd argument to TRUE:"
```
in the OP?
